# docker-compose.yml
version: '3.8'
services:
  postgres_db:
    image: postgres:13
    # latest 대신 13을 명시한 이유는 '재현성' 보장을 위해서.
    container_name: postgres_db
    environment:
      # 외부에서 설정을 주입하는 방법 (환경변수와 같음)
      # 설정 정보를 코드와 분리하는건 'Twelve-Factor App' 방법론의 핵심 원칙 중 하나.
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
